mfcc:
  sample_rate: 16000
  n_mfcc: 40
  max_pad_len: 128
  input_channels: 1
  storage_format: xlsx
  normalize: false
  selected_score_dims:
    - Vibrato
    - Throat
    - Position
    - Open
    - Clean
    - Resonate
    - Unify
    - Falsetto
    - Chest
    - Nasal
